### ISSUE TITLE
Minor suggestions

### ISSUE THREAD

**Issue by mschart** [int-brain-lab/iblvideo#1]
Hi Guido, Great updates! Just couple minor suggestions. Why not put the CaptureCamera.py as a function and then launch it with the camera index as input when looping through the subprocesses in MasterVideo. Like that the number of cameras is flexible and you have less scripts.

Also, worth pointing out differences of the subprocess approach to CaptureVideoMultithreading.py. There you set the buffer mode explicitly - which was crucial for image acquisition stability - but where is that buffer mode activation for the CaptureCamera scripts? 

Also, in CameraFunctions, CloseCameras takes framerate as input? That's a typo, right?

**Comment by guidomeijer** [comment]
Thanks for the feedback! I made the number of cameras flexible in the latest commit. However, I don't think the number of scripts can be reduced because they have to be launched with a bash command. I don't know if you can provide input to a python function using a bash command. Now it just runs the python script with the bash command 'python /path/to/script.py'

Using the subprocesses I actually don't have to use buffer mode for good performance. On the contrary, using buffer mode with subprocesses can result in a segmentation error when providing too many buffers. Probably because the subprocesses all use the same RAM hardware which can apparently result in that multiple processes try to access the same RAM space. 

Yes, that's a typo, thanks!

**Comment by mschart** [comment]
Cool, thanks, I see. 

Sure you can pass an integer into a python script by writing it in the terminal like so:

python script.py 5

And in the python script you get that 5 like so:

#!/usr/bin/env python    
from sys import argv 

camindex= int(argv)

print(camindex)

**Comment by guidomeijer** [comment]
Great suggestion, thanks! It's done!
